changelog:
  categories:
    - title: 🏕 Features and fixes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
